import { GeneralSettings } from '@/components/GeneralSettings';
import { Title } from '@/components/layout/Title';
import { GeistLink } from '@/components/ui/GeistLink';
import { Tabs } from '@geist-ui/core';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function MainDashboard() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>SPA-Geist-Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Tabs value={router.pathname} onChange={(route) => router.push(route)}>
        <Tabs.Item label='Overview' value='/dashboard/overview'>
          <Title>Overview</Title>
        </Tabs.Item>
        <Tabs.Item label='Reports' value='/dashboard/reports'>
          <Title>Reports</Title>
        </Tabs.Item>
        <Tabs.Item label='Activity' value='3'>
          <Title>Activity</Title>
        </Tabs.Item>
        <Tabs.Item label='Domains' value='4'>
          <Title>Domains</Title>
        </Tabs.Item>
        <Tabs.Item label='Usage' value='5'>
          <Title>Usage</Title>
        </Tabs.Item>
        <Tabs.Item label='Integrations' value='6'>
          <Title>Integrations</Title>
        </Tabs.Item>
        <Tabs.Item label='Settings' value='/dashboard/settings'>
          <Title>Personal Account Settings</Title>
          <div className='flex flex-row justify-center p-12'>
            <div className='flex flex-row space-x-4'>
              <nav className='flex flex-col'>
                <GeistLink route={''}>General</GeistLink>
                <GeistLink route={''}>Advanced</GeistLink>
                <GeistLink route={''}>Theme</GeistLink>
                <GeistLink route={''}>Other</GeistLink>
                <GeistLink route={''}>Teams</GeistLink>
              </nav>

              <div className='w-[910px] space-y-8'>
                <GeneralSettings />
              </div>
            </div>
          </div>
        </Tabs.Item>
      </Tabs>

      {/* <EmailVerify /> */}
    </>
  );
}
